# Generated by Django 3.2.5 on 2021-08-18 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_auto_20210818_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
