# Generated by Django 3.2.5 on 2021-08-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_remove_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Store', 'Store'), ('Inventory', 'Inventory'), ('Production', 'Production'), ('Quality Control', 'Quality Control'), ('QC_Analyst', 'QC_Analyst'), ('Quality Assurance', 'Quality Assurance'), ('RD', 'RD')], max_length=255),
        ),
    ]
