# Generated by Django 3.2.5 on 2021-09-03 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Production', '0005_auto_20210903_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='NCCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('subCategory', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='NCR',
            fields=[
                ('date', models.DateField(auto_now=True)),
                ('NCRNo', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='OPEN', max_length=20)),
                ('originator', models.CharField(max_length=30)),
                ('section', models.CharField(max_length=30)),
                ('sourceOfIdentification', models.CharField(max_length=30)),
                ('refNo', models.CharField(max_length=30)),
                ('natureOfNC', models.CharField(max_length=30)),
                ('gradeOfNC', models.CharField(max_length=30)),
                ('descriptionOFNonConformance', models.CharField(max_length=100)),
                ('solutionOfCurrentProblem', models.CharField(max_length=30)),
                ('immediateAction', models.CharField(max_length=30)),
                ('isActionTaken', models.BooleanField()),
                ('actionDate', models.DateField()),
                ('verifiedBy', models.CharField(max_length=30)),
                ('isLimitAction', models.BooleanField()),
                ('rootCause', models.CharField(blank=True, max_length=100, null=True)),
                ('proposedCorrectiveAction', models.CharField(blank=True, max_length=100, null=True)),
                ('actionTaken', models.CharField(blank=True, max_length=100, null=True)),
                ('NCCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='QualityAssurance.nccategory')),
                ('batchNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BNo', to='Production.bprlog')),
            ],
        ),
    ]
