# Generated by Django 3.2.5 on 2021-11-09 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QualityAssurance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drfitems',
            name='DRFNo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='drf', to='QualityAssurance.drf'),
            preserve_default=False,
        ),
    ]
