# Generated by Django 3.2.5 on 2021-09-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QualityAssurance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ncr',
            name='NCCategory',
        ),
        migrations.AddField(
            model_name='ncr',
            name='category',
            field=models.CharField(default='1', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ncr',
            name='subCategory',
            field=models.CharField(default='2', max_length=30),
            preserve_default=False,
        ),
    ]
