# Generated by Django 3.2.5 on 2021-09-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QualityAssurance', '0002_auto_20210903_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncr',
            name='closingDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ncr',
            name='actionDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
