# Generated by Django 3.2.5 on 2021-11-09 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0018_alter_pmpurchaseorders_dno'),
        ('QualityAssurance', '0002_drfitems_drfno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drfitems',
            name='RMCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.rawmaterials'),
        ),
    ]
