# Generated by Django 3.2.5 on 2021-09-04 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0005_auto_20210903_1638'),
        ('QualityAssurance', '0002_auto_20210904_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncr',
            name='batchNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BN', to='Production.bprlog'),
        ),
        migrations.CreateModel(
            name='BatchDeviation',
            fields=[
                ('date', models.DateField(auto_now=True)),
                ('deviationNo', models.AutoField(primary_key=True, serialize=False)),
                ('stage', models.CharField(max_length=50)),
                ('keyword', models.CharField(max_length=30)),
                ('descriptionOfDeviation', models.CharField(blank=True, max_length=200, null=True)),
                ('actionTaken', models.CharField(blank=True, max_length=100, null=True)),
                ('batchNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BNo', to='Production.bprlog')),
            ],
        ),
    ]
