# Generated by Django 3.2.5 on 2021-11-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QualityAssurance', '0003_alter_drfitems_rmcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changecontrol',
            name='degreeOfImplementation',
        ),
        migrations.AlterField(
            model_name='changecontrol',
            name='changeDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='changecontrol',
            name='implementedChanges',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='changecontrol',
            name='verifiedBy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
