# Generated by Django 3.2.5 on 2021-09-04 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0005_auto_20210903_1638'),
        ('QualityAssurance', '0003_auto_20210904_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeControl',
            fields=[
                ('date', models.DateField(auto_now=True)),
                ('CCNo', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='OPEN', max_length=20)),
                ('initiator', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('natureOfChange', models.CharField(max_length=30)),
                ('keyword', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('QAStatus', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('relatedChanges', models.CharField(max_length=200)),
                ('descriptionOfChange', models.CharField(max_length=200)),
                ('intendedPurposeOfChange', models.CharField(max_length=200)),
                ('commentsOfProductionManager', models.CharField(blank=True, max_length=200, null=True)),
                ('commentsOfQCManager', models.CharField(blank=True, max_length=200, null=True)),
                ('commentsOfPlantDirector', models.CharField(max_length=200)),
                ('commentsOfQAManager', models.CharField(max_length=200)),
                ('batchNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Production.bprlog')),
            ],
        ),
    ]
