# Generated by Django 3.2.5 on 2021-09-07 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0007_alter_pmformulation_packsize'),
        ('QualityAssurance', '0004_changecontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchdeviation',
            name='status',
            field=models.CharField(default='CLOSED', max_length=20),
        ),
        migrations.AlterField(
            model_name='batchdeviation',
            name='batchNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BDNo', to='Production.bprlog'),
        ),
        migrations.AlterField(
            model_name='changecontrol',
            name='batchNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BR', to='Production.bprlog'),
        ),
        migrations.CreateModel(
            name='BatchReview',
            fields=[
                ('date', models.DateField(auto_now=True)),
                ('BRNo', models.AutoField(primary_key=True, serialize=False)),
                ('dispatchPermission', models.CharField(max_length=30)),
                ('permittedDispatch', models.CharField(max_length=30)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('batchNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BRNo', to='Production.bprlog')),
            ],
        ),
    ]
