# Generated by Django 3.2.5 on 2021-11-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QualityAssurance', '0004_auto_20211129_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='changecontrol',
            name='degreeOfImplementation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
