# Generated by Django 3.2.5 on 2021-11-09 19:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0018_alter_pmpurchaseorders_dno'),
        ('Products', '0037_alter_packsizes_unique_together'),
        ('QualityAssurance', '0005_auto_20210907_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='changecontrol',
            name='changeDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='changecontrol',
            name='degreeOfImplementation',
            field=models.CharField(default='o', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='changecontrol',
            name='implementedChanges',
            field=models.CharField(default='q', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='changecontrol',
            name='verifiedBy',
            field=models.CharField(default='aa', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DRFItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formulaQuantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('additionalQuantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('RMCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DRFItem', to='Inventory.rawmaterials')),
            ],
        ),
        migrations.CreateModel(
            name='DRF',
            fields=[
                ('DRFNo', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(auto_now=True)),
                ('BatchNo', models.CharField(max_length=20)),
                ('ProductCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drf', to='Products.products')),
            ],
        ),
    ]
