# Generated by Django 3.2.5 on 2021-09-07 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QualityAssurance', '0005_batchreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BatchReview',
        ),
    ]
