# Generated by Django 3.2.5 on 2021-09-07 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0008_alter_bprlog_batchstatus'),
        ('QualityAssurance', '0006_delete_batchreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchReview',
            fields=[
                ('date', models.DateField(auto_now=True)),
                ('BRNo', models.AutoField(primary_key=True, serialize=False)),
                ('dispatchPermission', models.CharField(max_length=30)),
                ('permittedDispatch', models.CharField(max_length=30)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('batchNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BR', to='Production.bprlog')),
            ],
        ),
    ]
