# Generated by Django 3.2.5 on 2021-11-09 06:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('QualityAssurance', '0006_auto_20211109_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='changecontrol',
            name='changeDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
