# Generated by Django 3.2.5 on 2021-11-09 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0037_alter_packsizes_unique_together'),
        ('Inventory', '0018_alter_pmpurchaseorders_dno'),
        ('QualityAssurance', '0006_auto_20211110_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='DRFItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formulaQuantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('additionalQuantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('RMCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DRFItem', to='Inventory.rawmaterials')),
            ],
        ),
        migrations.CreateModel(
            name='DRF',
            fields=[
                ('DRFNo', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(auto_now=True)),
                ('BatchNo', models.CharField(max_length=20)),
                ('ProductCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drf', to='Products.products')),
            ],
        ),
    ]
