# Generated by Django 3.2.5 on 2021-09-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QualityAssurance', '0007_batchreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchdeviation',
            name='status',
            field=models.CharField(default='CLOSED', max_length=20),
        ),
    ]
