# Generated by Django 3.2.5 on 2021-11-09 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QualityAssurance', '0007_drf_drfitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drfitems',
            name='RMCode',
        ),
        migrations.DeleteModel(
            name='DRF',
        ),
        migrations.DeleteModel(
            name='DRFItems',
        ),
    ]
