# Generated by Django 3.2.5 on 2021-11-09 19:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0018_alter_pmpurchaseorders_dno'),
        ('QualityAssurance', '0008_drf_drfitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='drfitems',
            name='DRFNo',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='drfItem', to='QualityAssurance.drf'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drfitems',
            name='RMCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DRFItem', to='Inventory.rawmaterials'),
        ),
    ]
