# Generated by Django 3.2.5 on 2021-11-09 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QualityAssurance', '0009_auto_20211110_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drfitems',
            name='DRFNo',
        ),
    ]
