# Generated by Django 3.2.5 on 2021-08-30 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0036_stages'),
        ('Planning', '0008_auto_20210818_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=20)),
                ('dosageForm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form', to='Products.dosageforms')),
            ],
        ),
        migrations.CreateModel(
            name='BPRLog',
            fields=[
                ('batchNo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('openingDate', models.DateField()),
                ('closingDate', models.DateField(blank=True, null=True)),
                ('batchSize', models.IntegerField()),
                ('MFGDate', models.DateField()),
                ('EXPDate', models.DateField()),
                ('batchStatus', models.CharField(default='OPEN', max_length=10)),
                ('currentStage', models.CharField(max_length=20)),
                ('packed', models.IntegerField(default=0)),
                ('inProcess', models.IntegerField()),
                ('yieldPercentage', models.FloatField()),
                ('ProductCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proCode', to='Products.products')),
                ('planNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planN', to='Planning.plan')),
            ],
        ),
        migrations.CreateModel(
            name='BatchStages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openingDate', models.DateField()),
                ('closingDate', models.DateField()),
                ('currentStage', models.CharField(max_length=20)),
                ('units', models.CharField(max_length=10)),
                ('theoreticalYield', models.IntegerField()),
                ('actualYield', models.IntegerField()),
                ('yieldPercentage', models.FloatField()),
                ('PartialStatus', models.CharField(max_length=10)),
                ('remarks', models.TextField(max_length=100)),
                ('batchNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bNo', to='Production.bprlog')),
            ],
        ),
        migrations.CreateModel(
            name='BatchIssuanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noOfBatches', models.IntegerField()),
                ('ProductCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pCode', to='Products.products')),
                ('planNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='Planning.plan')),
            ],
        ),
    ]
