# Generated by Django 3.2.5 on 2021-09-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0004_alter_packinglog_totalpacks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchstages',
            name='PartialStatus',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='batchstages',
            name='currentStage',
            field=models.CharField(max_length=50),
        ),
    ]
