# Generated by Django 3.2.5 on 2021-09-05 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0036_stages'),
        ('Inventory', '0018_alter_pmpurchaseorders_dno'),
        ('Production', '0005_auto_20210903_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='PMFormulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchSize', models.IntegerField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('date', models.DateField()),
                ('docNo', models.CharField(max_length=10)),
                ('version', models.DecimalField(decimal_places=1, default=1.0, max_digits=4)),
                ('PMCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.packingmaterials')),
                ('PackSize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.packsizes')),
                ('ProductCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.products')),
            ],
        ),
    ]
