# Generated by Django 3.2.5 on 2021-09-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0006_pmformulation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmformulation',
            name='PackSize',
            field=models.CharField(max_length=20),
        ),
    ]
