# Generated by Django 3.2.5 on 2021-09-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0007_alter_pmformulation_packsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bprlog',
            name='batchStatus',
            field=models.CharField(default='OPEN', max_length=100),
        ),
    ]
