# Generated by Django 3.2.5 on 2021-09-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0007_alter_pmformulation_packsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bprlog',
            name='batchNo',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bprlog',
            name='batchStatus',
            field=models.CharField(default='OPEN', max_length=50),
        ),
        migrations.AlterField(
            model_name='bprlog',
            name='currentStage',
            field=models.CharField(default='ISSUED', max_length=50),
        ),
    ]
