# Generated by Django 3.2.5 on 2021-08-01 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('S_ID', models.AutoField(primary_key=True, serialize=False)),
                ('S_Name', models.CharField(max_length=50)),
                ('S_Email', models.EmailField(max_length=254)),
                ('S_Address', models.CharField(max_length=50)),
                ('S_City', models.CharField(max_length=50)),
                ('S_Country', models.CharField(max_length=50)),
                ('S_Phone', models.CharField(max_length=50)),
                ('materialType', models.CharField(max_length=2)),
                ('contactPersonName', models.CharField(max_length=50)),
                ('contactPersonPhone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierApprovedItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MCode', models.CharField(max_length=20)),
                ('S_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MaterialSuppliers.suppliers')),
            ],
        ),
    ]
