# Generated by Django 3.2.5 on 2021-08-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialSuppliers', '0002_auto_20210805_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierapproveditems',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
