# Generated by Django 3.2.5 on 2021-11-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialSuppliers', '0003_alter_supplierapproveditems_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliers',
            name='materialType',
        ),
        migrations.AddField(
            model_name='supplierapproveditems',
            name='materialType',
            field=models.CharField(default='RM', max_length=2),
            preserve_default=False,
        ),
    ]
