# Generated by Django 3.2.9 on 2022-04-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialSuppliers', '0004_auto_20211114_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='S_Name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
