# Generated by Django 3.2.5 on 2021-08-14 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0031_rename_registrationno_packsizes_productcode'),
        ('Inventory', '0013_auto_20210812_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('planNo', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PackSize', models.CharField(max_length=20)),
                ('requiredQuantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inHandQuantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ProductCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.products')),
                ('RMCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.rawmaterials')),
                ('planNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Planning.plan')),
            ],
        ),
        migrations.CreateModel(
            name='PlanItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PackSize', models.CharField(max_length=20)),
                ('required', models.DecimalField(decimal_places=3, max_digits=10)),
                ('inHand', models.IntegerField()),
                ('planned', models.IntegerField()),
                ('noOfBatches', models.DecimalField(decimal_places=3, max_digits=5)),
                ('achieved', models.IntegerField(default=0)),
                ('pending', models.IntegerField()),
                ('status', models.CharField(default='OPEN', max_length=10)),
                ('ProductCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.products')),
                ('planNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Planning.plan')),
            ],
        ),
    ]
