# Generated by Django 3.2.5 on 2021-08-15 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Planning', '0002_auto_20210815_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planitems',
            old_name='plannedPacks',
            new_name='packsToBePlanned',
        ),
    ]
