# Generated by Django 3.2.5 on 2021-08-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planning', '0004_productmaterials_demandedquantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaterials',
            name='demandedQuantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
