# Generated by Django 3.2.5 on 2021-08-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planning', '0006_productmaterials_workablebatches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaterials',
            name='workableBatches',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
