# Generated by Django 3.2.5 on 2021-08-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planning', '0007_alter_productmaterials_workablebatches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planitems',
            name='noOfBatchesToBePlanned',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productmaterials',
            name='workableBatches',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
