# Generated by Django 3.2.9 on 2021-12-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planning', '0008_auto_20210818_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='isSaved',
            field=models.BooleanField(default=False),
        ),
    ]
