# Generated by Django 3.2.5 on 2021-09-01 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0036_stages'),
        ('Planning', '0008_auto_20210818_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planitems',
            name='ProductCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='Products.products'),
        ),
    ]
