# Generated by Django 3.2.9 on 2021-12-25 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0040_delete_pm_formulation'),
        ('Inventory', '0020_delete_fgstock'),
        ('Planning', '0009_plan_issaved'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPackingMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PackSize', models.CharField(max_length=20)),
                ('requiredQuantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inHandQuantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('demandedQuantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('workableBatches', models.DecimalField(decimal_places=3, max_digits=10)),
                ('PMCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.packingmaterials')),
                ('ProductCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.products')),
                ('planNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Planning.plan')),
            ],
        ),
    ]
