# Generated by Django 3.2.5 on 2021-09-01 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0036_stages'),
        ('Planning', '0009_alter_planitems_productcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planitems',
            name='ProductCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.products'),
        ),
        migrations.AlterField(
            model_name='planitems',
            name='planNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planItems', to='Planning.plan'),
        ),
    ]
