# Generated by Django 3.2.5 on 2021-08-01 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialSuppliers', '0001_initial'),
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmdemands',
            name='PoNo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RMPurchaseOrders',
            fields=[
                ('PONo', models.BigAutoField(primary_key=True, serialize=False)),
                ('PODate', models.DateTimeField(auto_now_add=True)),
                ('DNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.rmdemands')),
            ],
        ),
        migrations.CreateModel(
            name='RMPurchaseOrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.FloatField(max_length=10)),
                ('Pending', models.FloatField(blank=True, max_length=10, null=True)),
                ('Received', models.FloatField(default=0, max_length=10)),
                ('Status', models.CharField(default='OPEN', max_length=10)),
                ('CommittedDate', models.DateField(blank=True, null=True)),
                ('Reason', models.CharField(default='', max_length=10)),
                ('PONo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.rmpurchaseorders')),
                ('RMCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.rawmaterials')),
                ('SID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MaterialSuppliers.suppliers')),
            ],
        ),
    ]
