# Generated by Django 3.2.5 on 2021-08-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_auto_20210801_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmpurchaseorderitems',
            name='Reason',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
