# Generated by Django 3.2.5 on 2021-08-03 06:57

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialSuppliers', '0001_initial'),
        ('Inventory', '0005_alter_rmdemandeditems_quantitypending'),
    ]

    operations = [
        migrations.CreateModel(
            name='RMReceiving',
            fields=[
                ('IGPNo', models.AutoField(primary_key=True, serialize=False)),
                ('RMCode', models.CharField(max_length=20)),
                ('quantityReceived', models.DecimalField(decimal_places=2, max_digits=10)),
                ('containersReceived', models.IntegerField()),
                ('batchNo', models.CharField(max_length=20, unique=True)),
                ('IGPDate', models.DateTimeField(auto_now_add=True)),
                ('GRNo', models.IntegerField(blank=True, null=True, unique=True)),
                ('MFG_Date', models.DateField(blank=True, null=True)),
                ('EXP_Date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='QUARANTINED', max_length=20)),
                ('quantityApproved', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('quantityRejected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('approval_Date', models.DateField(blank=True, null=True)),
                ('QCNo', models.CharField(blank=True, max_length=20, null=True)),
                ('remarks', models.TextField(blank=True, max_length=100, null=True)),
                ('retest_Date', models.DateField(blank=True, null=True)),
                ('PONo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.rmpurchaseorders')),
                ('S_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MaterialSuppliers.suppliers')),
            ],
        ),
    ]
