# Generated by Django 3.2.5 on 2021-08-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0006_rmreceiving'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmdemands',
            name='demandStatus',
            field=models.CharField(default='PENDING', max_length=10),
        ),
    ]
