# Generated by Django 3.2.5 on 2021-08-04 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0007_rmdemands_demandstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='RMBinCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField(auto_now_add=True)),
                ('particulars', models.CharField(blank=True, max_length=20, null=True)),
                ('batchNo', models.CharField(max_length=20, unique=True)),
                ('received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issued', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('QCNo', models.CharField(max_length=20)),
                ('GRBalance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('RMCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.rawmaterials')),
            ],
        ),
    ]
