# Generated by Django 3.2.5 on 2021-08-07 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0009_auto_20210805_1654'),
        ('Inventory', '0009_rmpurchaseorders_status'),
    ]

    operations = [
    ]
