# Generated by Django 3.2.5 on 2021-08-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0011_auto_20210807_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmreceiving',
            name='GRNo',
            field=models.IntegerField(default=0),
        ),
    ]
