# Generated by Django 3.2.5 on 2021-08-26 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0013_auto_20210812_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmreceiving',
            name='RMCode',
            field=models.ForeignKey(default='1.01.001.00051', on_delete=django.db.models.deletion.CASCADE, to='Inventory.rawmaterials'),
        ),
    ]
