# Generated by Django 3.2.5 on 2021-08-26 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0014_alter_rmreceiving_rmcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmreceiving',
            name='PMCode',
            field=models.ForeignKey(default='3.02.003.00019', on_delete=django.db.models.deletion.CASCADE, to='Inventory.rawmaterials'),
        ),
        migrations.AlterField(
            model_name='rmreceiving',
            name='RMCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.rawmaterials'),
        ),
    ]
