# Generated by Django 3.2.5 on 2021-08-26 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0015_auto_20210826_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmreceiving',
            name='PMCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.rawmaterials'),
        ),
    ]
