# Generated by Django 3.2.5 on 2021-08-30 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0016_alter_pmreceiving_pmcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmreceiving',
            name='PMCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.packingmaterials'),
        ),
    ]
