# Generated by Django 3.2.5 on 2021-09-03 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0017_alter_pmreceiving_pmcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmpurchaseorders',
            name='DNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.pmdemands'),
        ),
    ]
