# Generated by Django 3.2.9 on 2021-12-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0018_alter_pmpurchaseorders_dno'),
    ]

    operations = [
        migrations.CreateModel(
            name='FGStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField(auto_now_add=True)),
                ('particulars', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
