# Generated by Django 3.2.9 on 2021-12-17 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0019_fgstock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FGStock',
        ),
    ]
