# Generated by Django 3.2.9 on 2022-04-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0020_delete_fgstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterials',
            name='Date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
