# Generated by Django 3.2.9 on 2022-04-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0021_rawmaterials_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='packingmaterials',
            name='Date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
