# Generated by Django 3.2.5 on 2021-08-20 18:25

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0033_alter_packsizes_packtype'),
        ('Inventory', '0013_auto_20210812_1218'),
        ('QualityControl', '0002_alter_rmspecifications_rmcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PMParameters',
            fields=[
                ('parameter', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PMSpecifications',
            fields=[
                ('specID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('version', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=3)),
                ('SOPNo', models.CharField(max_length=20, unique=True)),
                ('QAStatus', models.CharField(default='ALLOWED', max_length=10)),
                ('PMCode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Inventory.packingmaterials')),
            ],
        ),
        migrations.CreateModel(
            name='ProductParameters',
            fields=[
                ('parameter', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpecifications',
            fields=[
                ('specID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('stage', models.CharField(max_length=20)),
                ('version', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=3)),
                ('SOPNo', models.CharField(max_length=20, unique=True)),
                ('QAStatus', models.CharField(default='ALLOWED', max_length=10)),
                ('ProductCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.products')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpecificationsItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.TextField(max_length=200)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QualityControl.productparameters')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QualityControl.rmreferences')),
                ('specID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QualityControl.productspecifications')),
            ],
        ),
        migrations.CreateModel(
            name='PMSpecificationsItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.TextField(max_length=200)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QualityControl.pmparameters')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QualityControl.rmreferences')),
                ('specID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QualityControl.pmspecifications')),
            ],
        ),
    ]
