# Generated by Django 3.2.5 on 2021-08-22 08:16

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0013_auto_20210812_1218'),
        ('QualityControl', '0004_auto_20210822_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='RMSpecifications',
            fields=[
                ('specID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('version', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=3)),
                ('SOPNo', models.CharField(max_length=20, unique=True)),
                ('QAStatus', models.CharField(default='ALLOWED', max_length=10)),
                ('RMCode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Inventory.rawmaterials')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QualityControl.rmreferences')),
            ],
        ),
        migrations.CreateModel(
            name='RMSpecificationsItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.TextField(max_length=200)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QualityControl.rmparameters')),
                ('specID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QualityControl.rmspecifications')),
            ],
        ),
    ]
