# Generated by Django 3.2.5 on 2021-08-23 07:10

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Inventory', '0013_auto_20210812_1218'),
        ('QualityControl', '0005_rmspecifications_rmspecificationsitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempRMSpecifications',
            fields=[
                ('specID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('version', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=3)),
                ('SOPNo', models.CharField(max_length=20, unique=True)),
                ('QAStatus', models.CharField(default='EDIT', max_length=10)),
                ('RMCode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Inventory.rawmaterials')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QualityControl.rmreferences')),
            ],
        ),
        migrations.AddField(
            model_name='rmsamples',
            name='samplingDateTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rmsamples',
            name='analyst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rmsamples',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='TempRMSpecificationsItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.TextField(max_length=200)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QualityControl.rmparameters')),
                ('specID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QualityControl.temprmspecifications')),
            ],
        ),
    ]
