# Generated by Django 3.2.5 on 2021-08-24 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QualityControl', '0006_auto_20210823_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rmsamples',
            name='analyst',
        ),
    ]
