# Generated by Django 3.2.5 on 2021-08-23 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QualityControl', '0007_alter_rmspecificationsitems_specid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temprmspecificationsitems',
            name='specID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='QualityControl.temprmspecifications'),
        ),
    ]
