# Generated by Django 3.2.5 on 2021-08-24 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QualityControl', '0007_remove_rmsamples_analyst'),
    ]

    operations = [
        migrations.CreateModel(
            name='RMAnalysis',
            fields=[
                ('RMAnalysisID', models.AutoField(primary_key=True, serialize=False)),
                ('workingStd', models.CharField(max_length=40)),
                ('rawDataReference', models.CharField(max_length=40)),
                ('analysisDateTime', models.DateTimeField(blank=True, null=True)),
                ('retestDate', models.DateTimeField(blank=True, null=True)),
                ('quantityApproved', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantityRejected', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.CharField(blank=True, max_length=40, null=True)),
                ('specID', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='rmsamples',
            name='analyst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RMAnalysisLog',
            fields=[
                ('RMAnalysisID', models.AutoField(primary_key=True, serialize=False)),
                ('workingStd', models.CharField(max_length=40)),
                ('rawDataReference', models.CharField(max_length=40)),
                ('analysisDateTime', models.DateTimeField(blank=True, null=True)),
                ('retestDate', models.DateTimeField(blank=True, null=True)),
                ('quantityApproved', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantityRejected', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.CharField(blank=True, max_length=40, null=True)),
                ('specID', models.IntegerField()),
                ('QCNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QualityControl.rmsamples')),
            ],
        ),
        migrations.CreateModel(
            name='RMAnalysisItemsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=20)),
                ('specification', models.TextField(max_length=200)),
                ('result', models.CharField(max_length=20)),
                ('RMAnalysisID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QualityControl.rmanalysislog')),
            ],
        ),
        migrations.CreateModel(
            name='RMAnalysisItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=20)),
                ('specification', models.TextField(max_length=200)),
                ('result', models.CharField(max_length=20)),
                ('RMAnalysisID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QualityControl.rmanalysis')),
            ],
        ),
        migrations.AddField(
            model_name='rmanalysis',
            name='QCNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QualityControl.rmsamples'),
        ),
    ]
