# Generated by Django 3.2.5 on 2021-08-26 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QualityControl', '0008_auto_20210824_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmspecificationsitems',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='QualityControl.rmparameters'),
        ),
        migrations.AlterField(
            model_name='rmspecificationsitems',
            name='specID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RMSpecsItems', to='QualityControl.rmspecifications'),
        ),
    ]
