# Generated by Django 3.2.5 on 2021-08-25 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QualityControl', '0008_auto_20210824_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmanalysisitems',
            name='RMAnalysisID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rm_analysis_items', to='QualityControl.rmanalysis'),
        ),
    ]
