# Generated by Django 3.2.5 on 2021-08-24 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0013_auto_20210812_1218'),
        ('QualityControl', '0008_alter_temprmspecificationsitems_specid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmsamples',
            name='IGPNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rmsamples', to='Inventory.rmreceiving'),
        ),
    ]
