# Generated by Django 3.2.5 on 2021-08-24 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QualityControl', '0009_alter_rmsamples_igpno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rmsamples',
            name='analyst',
        ),
    ]
