# Generated by Django 3.2.5 on 2021-08-24 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QualityControl', '0011_rmsamples_analyst'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RMSamples',
        ),
    ]
