# Generated by Django 3.2.5 on 2021-08-30 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QualityControl', '0012_alter_rmanalysislog_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pmspecifications',
            name='PMCode',
        ),
        migrations.RemoveField(
            model_name='pmspecificationsitems',
            name='parameter',
        ),
        migrations.RemoveField(
            model_name='pmspecificationsitems',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='pmspecificationsitems',
            name='specID',
        ),
        migrations.RemoveField(
            model_name='productspecifications',
            name='ProductCode',
        ),
        migrations.RemoveField(
            model_name='productspecificationsitems',
            name='parameter',
        ),
        migrations.RemoveField(
            model_name='productspecificationsitems',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='productspecificationsitems',
            name='specID',
        ),
        migrations.DeleteModel(
            name='PMParameters',
        ),
        migrations.DeleteModel(
            name='PMSpecifications',
        ),
        migrations.DeleteModel(
            name='PMSpecificationsItems',
        ),
        migrations.DeleteModel(
            name='ProductParameters',
        ),
        migrations.DeleteModel(
            name='ProductSpecifications',
        ),
        migrations.DeleteModel(
            name='ProductSpecificationsItems',
        ),
    ]
