# Generated by Django 3.2.5 on 2021-08-30 11:37

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0016_alter_pmreceiving_pmcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QualityControl', '0013_auto_20210830_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='PMAnalysis',
            fields=[
                ('PMAnalysisID', models.AutoField(primary_key=True, serialize=False)),
                ('workingStd', models.CharField(max_length=40)),
                ('rawDataReference', models.CharField(max_length=40)),
                ('analysisDateTime', models.DateTimeField(blank=True, null=True)),
                ('retestDate', models.DateTimeField(blank=True, null=True)),
                ('quantityApproved', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantityRejected', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.CharField(blank=True, max_length=40, null=True)),
                ('specID', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PMParameters',
            fields=[
                ('parameter', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PMSpecifications',
            fields=[
                ('specID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('version', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=3)),
                ('SOPNo', models.CharField(max_length=20, unique=True)),
                ('QAStatus', models.CharField(default='ALLOWED', max_length=10)),
                ('PMCode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Inventory.packingmaterials')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QualityControl.rmreferences')),
            ],
        ),
        migrations.CreateModel(
            name='TempPMSpecifications',
            fields=[
                ('specID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('version', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=3)),
                ('SOPNo', models.CharField(max_length=20, unique=True)),
                ('QAStatus', models.CharField(default='EDIT', max_length=10)),
                ('PMCode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Inventory.packingmaterials')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QualityControl.rmreferences')),
            ],
        ),
        migrations.CreateModel(
            name='TempPMSpecificationsItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.TextField(max_length=200)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QualityControl.pmparameters')),
                ('specID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QualityControl.temppmspecifications')),
            ],
        ),
        migrations.CreateModel(
            name='PMSpecificationsItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.TextField(max_length=200)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='QualityControl.pmparameters')),
                ('specID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RMSpecsItems', to='QualityControl.pmspecifications')),
            ],
        ),
        migrations.CreateModel(
            name='PMSamples',
            fields=[
                ('QCNo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('deliveredBy', models.CharField(max_length=40)),
                ('receivedBy', models.CharField(max_length=40)),
                ('samplingDateTime', models.DateTimeField(auto_now=True)),
                ('assignedDateTime', models.DateTimeField(blank=True, null=True)),
                ('analysisDateTime', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=50, null=True)),
                ('IGPNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.pmreceiving')),
                ('analyst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PMAnalysisLog',
            fields=[
                ('PMAnalysisID', models.AutoField(primary_key=True, serialize=False)),
                ('workingStd', models.CharField(max_length=40)),
                ('rawDataReference', models.CharField(max_length=40)),
                ('analysisDateTime', models.DateTimeField(blank=True, null=True)),
                ('retestDate', models.DateTimeField(blank=True, null=True)),
                ('quantityApproved', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantityRejected', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.CharField(blank=True, max_length=40, null=True)),
                ('specID', models.IntegerField()),
                ('result', models.CharField(max_length=20)),
                ('QCNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QualityControl.pmsamples')),
            ],
        ),
        migrations.CreateModel(
            name='PMAnalysisItemsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=20)),
                ('specification', models.TextField(max_length=200)),
                ('result', models.CharField(max_length=20)),
                ('PMAnalysisID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QualityControl.pmanalysislog')),
            ],
        ),
        migrations.CreateModel(
            name='PMAnalysisItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=20)),
                ('specification', models.TextField(max_length=200)),
                ('result', models.CharField(max_length=20)),
                ('PMAnalysisID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PMAnalysisID_ID', to='QualityControl.pmanalysis')),
            ],
        ),
        migrations.AddField(
            model_name='pmanalysis',
            name='QCNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QualityControl.pmsamples'),
        ),
    ]
