# Generated by Django 3.2.5 on 2021-09-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QualityControl', '0014_auto_20210830_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductParameters',
            fields=[
                ('parameter', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
    ]
