# Generated by Django 3.2.5 on 2021-09-04 11:38

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0036_stages'),
        ('QualityControl', '0015_productparameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpecifications',
            fields=[
                ('specID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('stage', models.CharField(max_length=30)),
                ('version', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=3)),
                ('SOPNo', models.CharField(max_length=20, unique=True)),
                ('QAStatus', models.CharField(default='ALLOWED', max_length=10)),
                ('ProductCode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Products.products')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QualityControl.rmreferences')),
            ],
        ),
        migrations.CreateModel(
            name='TempProductSpecifications',
            fields=[
                ('specID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('version', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=3)),
                ('SOPNo', models.CharField(max_length=20, unique=True)),
                ('QAStatus', models.CharField(default='EDIT', max_length=10)),
                ('ProductCode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Products.products')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QualityControl.rmreferences')),
            ],
        ),
        migrations.CreateModel(
            name='TempProductSpecificationsItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.TextField(max_length=200)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QualityControl.productparameters')),
                ('specID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QualityControl.tempproductspecifications')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpecificationsItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.TextField(max_length=200)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='QualityControl.productparameters')),
                ('specID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductSpecsItems', to='QualityControl.productspecifications')),
            ],
        ),
    ]
