# Generated by Django 3.2.5 on 2021-09-04 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Production', '0005_auto_20210903_1638'),
        ('QualityControl', '0016_productspecifications_productspecificationsitems_tempproductspecifications_tempproductspecifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAnalysis',
            fields=[
                ('ProductAnalysisID', models.AutoField(primary_key=True, serialize=False)),
                ('workingStd', models.CharField(max_length=40)),
                ('rawDataReference', models.CharField(max_length=40)),
                ('analysisDateTime', models.DateTimeField(blank=True, null=True)),
                ('retestDate', models.DateTimeField(blank=True, null=True)),
                ('quantityApproved', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantityRejected', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.CharField(blank=True, max_length=40, null=True)),
                ('specID', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSamples',
            fields=[
                ('QCNo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sampleStage', models.CharField(max_length=50)),
                ('deliveredBy', models.CharField(max_length=40)),
                ('receivedBy', models.CharField(max_length=40)),
                ('samplingDateTime', models.DateTimeField(auto_now=True)),
                ('assignedDateTime', models.DateTimeField(blank=True, null=True)),
                ('analysisDateTime', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=50, null=True)),
                ('analyst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('batchNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Production.bprlog')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAnalysisLog',
            fields=[
                ('ProductAnalysisID', models.AutoField(primary_key=True, serialize=False)),
                ('workingStd', models.CharField(max_length=40)),
                ('rawDataReference', models.CharField(max_length=40)),
                ('analysisDateTime', models.DateTimeField(blank=True, null=True)),
                ('retestDate', models.DateTimeField(blank=True, null=True)),
                ('quantityApproved', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantityRejected', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.CharField(blank=True, max_length=40, null=True)),
                ('specID', models.IntegerField()),
                ('result', models.CharField(max_length=20)),
                ('QCNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QualityControl.productsamples')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAnalysisItemsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=20)),
                ('specification', models.TextField(max_length=200)),
                ('result', models.CharField(max_length=20)),
                ('ProductAnalysisID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QualityControl.productanalysislog')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAnalysisItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=20)),
                ('specification', models.TextField(max_length=200)),
                ('result', models.CharField(max_length=20)),
                ('ProductAnalysisID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductAnalysisID_ID', to='QualityControl.productanalysis')),
            ],
        ),
        migrations.AddField(
            model_name='productanalysis',
            name='QCNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QualityControl.productsamples'),
        ),
    ]
