# Generated by Django 3.2.5 on 2021-09-04 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0036_stages'),
        ('QualityControl', '0017_auto_20210904_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecifications',
            name='ProductCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.products'),
        ),
        migrations.AlterField(
            model_name='tempproductspecifications',
            name='ProductCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.products'),
        ),
    ]
