# Generated by Django 3.2.5 on 2021-09-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QualityControl', '0018_auto_20210904_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempproductspecifications',
            name='stage',
            field=models.CharField(default='Bulk', max_length=30),
            preserve_default=False,
        ),
    ]
