# Generated by Django 3.2.5 on 2021-09-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QualityControl', '0019_tempproductspecifications_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsamples',
            name='sampleQuantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
