# Generated by Django 3.2.5 on 2021-09-05 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QualityControl', '0020_productsamples_samplequantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsamples',
            name='receivedBy',
        ),
    ]
