# Generated by Django 3.2.5 on 2021-09-05 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QualityControl', '0021_remove_productsamples_receivedby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsamples',
            old_name='deliveredBy',
            new_name='sampledBy',
        ),
    ]
