# Generated by Django 3.2.5 on 2021-09-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QualityControl', '0022_rename_deliveredby_productsamples_sampledby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsamples',
            name='sampleQuantity',
            field=models.CharField(max_length=20),
        ),
    ]
