# Generated by Django 3.2.5 on 2021-09-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QualityControl', '0023_alter_productsamples_samplequantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsamples',
            name='sampleUnity',
            field=models.CharField(default='ml', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productsamples',
            name='sampleQuantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
