# Generated by Django 3.2.9 on 2022-01-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QualityControl', '0025_alter_productspecifications_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmanalysislog',
            name='isPrinted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productanalysislog',
            name='isPrinted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rmanalysislog',
            name='isPrinted',
            field=models.BooleanField(default=False),
        ),
    ]
