# Generated by Django 3.2.9 on 2022-08-08 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0022_packingmaterials_date'),
        ('MaterialSuppliers', '0005_alter_suppliers_s_name'),
        ('QualityControl', '0026_auto_20220110_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rmsamples',
            name='IGPNo',
        ),
        migrations.AddField(
            model_name='rmsamples',
            name='EXP_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rmsamples',
            name='MFG_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rmsamples',
            name='RMCode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Inventory.rawmaterials'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rmsamples',
            name='S_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MaterialSuppliers.suppliers'),
        ),
        migrations.AddField(
            model_name='rmsamples',
            name='batchNo',
            field=models.CharField(default='ABC', max_length=20),
        ),
        migrations.AddField(
            model_name='rmsamples',
            name='quantityReceived',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
    ]
