# Generated by Django 3.2.9 on 2022-08-08 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QualityControl', '0031_auto_20220808_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rmsamples',
            name='EXP_Date',
        ),
        migrations.RemoveField(
            model_name='rmsamples',
            name='MFG_Date',
        ),
    ]
