# Generated by Django 3.2.9 on 2022-08-08 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QualityControl', '0032_auto_20220809_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmsamples',
            name='EXP_Date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='rmsamples',
            name='MFG_Date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
