# Generated by Django 3.2.9 on 2022-08-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QualityControl', '0033_auto_20220809_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmsamples',
            name='containersReceived',
            field=models.IntegerField(default=0),
        ),
    ]
