# Generated by Django 3.2.9 on 2022-08-28 08:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0022_packingmaterials_date'),
        ('MaterialSuppliers', '0005_alter_suppliers_s_name'),
        ('QualityControl', '0035_rmsamples_grn_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pmsamples',
            name='IGPNo',
        ),
        migrations.AddField(
            model_name='pmsamples',
            name='EXP_Date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='pmsamples',
            name='GRN_No',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pmsamples',
            name='MFG_Date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='pmsamples',
            name='PMCode',
            field=models.ForeignKey(default='3.01.024.00002', on_delete=django.db.models.deletion.CASCADE, to='Inventory.packingmaterials'),
        ),
        migrations.AddField(
            model_name='pmsamples',
            name='S_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MaterialSuppliers.suppliers'),
        ),
        migrations.AddField(
            model_name='pmsamples',
            name='batchNo',
            field=models.CharField(default='ABC', max_length=20),
        ),
        migrations.AddField(
            model_name='pmsamples',
            name='containersReceived',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pmsamples',
            name='quantityReceived',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
    ]
