# Generated by Django 3.2.9 on 2022-08-28 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialSuppliers', '0005_alter_suppliers_s_name'),
        ('Inventory', '0022_packingmaterials_date'),
        ('QualityControl', '0036_auto_20220828_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmsamples',
            name='PMCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.packingmaterials'),
        ),
        migrations.AlterField(
            model_name='pmsamples',
            name='S_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MaterialSuppliers.suppliers'),
        ),
        migrations.AlterField(
            model_name='pmsamples',
            name='batchNo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pmsamples',
            name='quantityReceived',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
