# Generated by Django 3.2.5 on 2022-09-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QualityControl', '0037_auto_20220828_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmparameters',
            name='parameter',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
