# Generated by Django 3.2.9 on 2022-08-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QualityControl', '0037_auto_20220828_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmsamples',
            name='GRN_No',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rmsamples',
            name='GRN_No',
            field=models.IntegerField(),
        ),
    ]
