# Generated by Django 3.2.5 on 2022-09-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QualityControl', '0038_alter_rmparameters_parameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmparameters',
            name='parameter',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
