# Generated by Django 3.2.5 on 2021-07-28 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DosageForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PackSize', models.CharField(max_length=20)),
                ('Type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ProductCode', models.CharField(max_length=5)),
                ('RegistrationNo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('RegistrationDate', models.DateField()),
                ('RenewalDate', models.DateField()),
                ('DosageForm', models.CharField(max_length=20)),
                ('GenericName', models.CharField(max_length=20)),
                ('Composition', models.CharField(max_length=20)),
                ('ShelfLife', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PackSizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PackSize', models.CharField(max_length=20)),
                ('MRP', models.FloatField()),
                ('RegistrationNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.products')),
            ],
        ),
    ]
