# Generated by Django 3.2.5 on 2021-07-29 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Product',
            field=models.CharField(default='No Name', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='packsizes',
            name='PackSize',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.dosageforms'),
        ),
    ]
