# Generated by Django 3.2.5 on 2021-07-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_auto_20210729_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packsizes',
            name='PackSize',
            field=models.CharField(max_length=20),
        ),
    ]
