# Generated by Django 3.2.5 on 2021-07-29 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_alter_packsizes_packsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packsizes',
            name='PackSize',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.dosageforms'),
        ),
    ]
