# Generated by Django 3.2.5 on 2021-07-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_alter_packsizes_packsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packsizes',
            name='PackSize',
            field=models.CharField(max_length=20),
        ),
    ]
