# Generated by Django 3.2.5 on 2021-07-29 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_alter_packsizes_packsize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dosageforms',
            name='id',
        ),
        migrations.AlterField(
            model_name='dosageforms',
            name='PackSize',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='packsizes',
            name='PackSize',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.dosageforms'),
        ),
    ]
