# Generated by Django 3.2.5 on 2021-07-29 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_auto_20210729_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterialTypes',
            fields=[
                ('Type', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RMCode', models.CharField(max_length=20)),
                ('Material', models.CharField(max_length=50)),
                ('Units', models.CharField(max_length=10)),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.rawmaterialtypes')),
            ],
        ),
    ]
