# Generated by Django 3.2.5 on 2021-07-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_packingmaterials_packingmaterialtypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosageforms',
            name='PackType',
            field=models.CharField(default=None, max_length=20, unique=True),
        ),
    ]
