# Generated by Django 3.2.5 on 2021-07-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_dosageforms_packtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosageforms',
            name='PackType',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
