# Generated by Django 3.2.5 on 2021-07-30 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_alter_dosageforms_packtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dosageforms',
            name='PackType',
        ),
    ]
