# Generated by Django 3.2.5 on 2021-07-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_remove_dosageforms_packtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosageforms',
            name='PackType',
            field=models.CharField(default='N/A', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
