# Generated by Django 3.2.5 on 2021-07-31 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0013_rmdemands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmdemands',
            name='CancelledDate',
            field=models.DateTimeField(blank=True),
        ),
    ]
