# Generated by Django 3.2.5 on 2021-07-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0014_alter_rmdemands_cancelleddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmdemands',
            name='CancelledDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
