# Generated by Django 3.2.5 on 2021-07-31 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0016_alter_rmdemands_cancelleddate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RMDemands',
        ),
    ]
