# Generated by Django 3.2.5 on 2021-07-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0018_rmdemands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmdemands',
            name='PoNo',
            field=models.IntegerField(max_length=4),
        ),
    ]
