# Generated by Django 3.2.5 on 2021-07-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0020_alter_rmdemands_cancelleddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmdemands',
            name='Status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
