# Generated by Django 3.2.5 on 2021-08-01 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0021_rmdemands_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterials',
            name='id',
        ),
        migrations.RemoveField(
            model_name='rmdemands',
            name='Priority',
        ),
        migrations.RemoveField(
            model_name='rmdemands',
            name='Status',
        ),
        migrations.AlterField(
            model_name='rawmaterials',
            name='RMCode',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rmdemands',
            name='PoNo',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
        migrations.CreateModel(
            name='RMDemandedItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Priority', models.CharField(max_length=20)),
                ('DemandedQty', models.FloatField(max_length=10)),
                ('CurrentStock', models.FloatField(default=0, max_length=10)),
                ('QuantityPending', models.FloatField(max_length=10)),
                ('Status', models.CharField(default='Pending', max_length=10)),
                ('DNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.rmdemands')),
                ('RMCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.rawmaterials')),
            ],
        ),
    ]
