# Generated by Django 3.2.5 on 2021-08-01 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0022_auto_20210801_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterials',
            name='Type',
        ),
        migrations.RemoveField(
            model_name='rmdemandeditems',
            name='DNo',
        ),
        migrations.RemoveField(
            model_name='rmdemandeditems',
            name='RMCode',
        ),
        migrations.DeleteModel(
            name='PackingMaterials',
        ),
        migrations.DeleteModel(
            name='PackingMaterialTypes',
        ),
        migrations.DeleteModel(
            name='RawMaterials',
        ),
        migrations.DeleteModel(
            name='RawMaterialTypes',
        ),
        migrations.DeleteModel(
            name='RMDemandedItems',
        ),
        migrations.DeleteModel(
            name='RMDemands',
        ),
    ]
