# Generated by Django 3.2.5 on 2021-08-09 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0025_alter_packsizes_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packsizes',
            name='PackSize',
        ),
        migrations.RemoveField(
            model_name='packsizes',
            name='RegistrationNo',
        ),
        migrations.DeleteModel(
            name='DosageForms',
        ),
        migrations.DeleteModel(
            name='PackSizes',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
