# Generated by Django 3.2.5 on 2021-08-09 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0026_auto_20210809_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='DosageForms',
            fields=[
                ('dosageForm', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PackSizesListForFrontEnd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PackSizes', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ProductCode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Product', models.CharField(max_length=30)),
                ('RegistrationNo', models.CharField(max_length=10, unique=True)),
                ('RegistrationDate', models.DateField()),
                ('RenewalDate', models.DateField()),
                ('GenericName', models.CharField(max_length=20)),
                ('Composition', models.CharField(max_length=20)),
                ('ShelfLife', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dosageForm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.dosageforms')),
            ],
        ),
        migrations.CreateModel(
            name='PackSizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PackSize', models.CharField(max_length=20)),
                ('PackType', models.CharField(max_length=20, unique=True)),
                ('MRP', models.FloatField()),
                ('RegistrationNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.products')),
            ],
        ),
    ]
