# Generated by Django 3.2.5 on 2021-08-09 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0027_dosageforms_packsizes_packsizeslistforfrontend_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PackSizesListForFrontEnd',
        ),
    ]
