# Generated by Django 3.2.5 on 2021-08-09 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0028_delete_packsizeslistforfrontend'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackSizesListForFrontEnd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PackSizes', models.CharField(max_length=20)),
                ('DosageForms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.dosageforms')),
            ],
        ),
    ]
