# Generated by Django 3.2.5 on 2021-08-09 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0011_auto_20210807_1208'),
        ('Products', '0029_packsizeslistforfrontend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchSize', models.IntegerField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('date', models.DateField()),
                ('docNo', models.CharField(max_length=10)),
                ('version', models.DecimalField(decimal_places=1, default=1.0, max_digits=4)),
                ('ProductCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.products')),
                ('RMCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.rawmaterials')),
            ],
        ),
    ]
