# Generated by Django 3.2.5 on 2021-08-14 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0030_formulation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packsizes',
            old_name='RegistrationNo',
            new_name='ProductCode',
        ),
    ]
