# Generated by Django 3.2.5 on 2021-08-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0031_rename_registrationno_packsizes_productcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosageforms',
            name='batchSizeUnit',
            field=models.CharField(default='units', max_length=20),
        ),
    ]
