# Generated by Django 3.2.5 on 2021-08-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0032_dosageforms_batchsizeunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packsizes',
            name='PackType',
            field=models.CharField(max_length=20),
        ),
    ]
