# Generated by Django 3.2.5 on 2021-08-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0033_alter_packsizes_packtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosageForm', models.CharField(max_length=20)),
                ('stage', models.CharField(max_length=20)),
            ],
        ),
    ]
