# Generated by Django 3.2.5 on 2021-08-21 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0034_stages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stages',
        ),
    ]
