# Generated by Django 3.2.5 on 2021-08-21 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0035_delete_stages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=20)),
                ('DosageForms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.dosageforms')),
            ],
        ),
    ]
