# Generated by Django 3.2.5 on 2021-09-07 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0036_stages'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='packsizes',
            unique_together={('PackSize', 'ProductCode')},
        ),
    ]
