# Generated by Django 3.2.5 on 2021-11-29 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0018_alter_pmpurchaseorders_dno'),
        ('Products', '0037_alter_packsizes_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='PM_Formulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PackSize', models.CharField(max_length=20)),
                ('batchSize', models.IntegerField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('date', models.DateField()),
                ('docNo', models.CharField(max_length=10)),
                ('version', models.DecimalField(decimal_places=1, default=1.0, max_digits=4)),
                ('PMCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PM_Form', to='Inventory.rawmaterials')),
                ('ProductCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PM_Formulation', to='Products.products')),
            ],
        ),
    ]
