# Generated by Django 3.2.5 on 2021-12-04 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0018_alter_pmpurchaseorders_dno'),
        ('Products', '0038_pm_formulation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pm_formulation',
            name='PMCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PM_Form', to='Inventory.packingmaterials'),
        ),
    ]
