# Generated by Django 3.2.9 on 2021-12-16 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0039_alter_pm_formulation_pmcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PM_Formulation',
        ),
    ]
